project:
  type: website

website:
  title: "From data analysis to publication: Reproducible research with R and Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: slides.qmd
        text: Slides

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

